language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: seantingwong-github
    token:
      secure: 3e86befc6ea5867181ce98348d2fe8f2fd237e6f
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
